export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_SUCCESS_MSG = "GET_SUCCESS_MSG";
export const RESET_ALL_STATE = "RESET_ALL_STATE";
export const RESET_SUCCESS_STATE = "RESET_SUCCESS_STATE";
export const RESET_ERROR_STATE = "RESET_ERROR_STATE";

export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const UPDATED_USER_PROFILE = "UPDATED_USER_PROFILE";

export const FETCH_SECTIONS = "FETCH_SECTIONS";
export const UPDATED_SECTION = "UPDATED_SECTION";

export const DELETE_SECTION = "DELETE_SECTION";

export const FETCH_SECTION_ITEM = "FETCH_SECTION_ITEM";
export const UPDATED_SECTION_ITEM = "UPDATED_SECTION_ITEM";
export const DELETE_SECTION_ITEM  = "DELETE_SECTION_ITEM";

export const SEARCH_ITEM_FOR_BUYER = "SEARCH_ITEM_FOR_BUYER";
export const FETCH_CUISINES = "FETCH_CUISINES";

export const FETCH_RESTAURANT_ALL_INFO = "FETCH_RESTAURANT_ALL_INFO";

export const UPDATE_CART = "UPDATE_CART";
export const GET_CART = "GET_CART";
export const RESET_CART_INFO = "RESET_CART_INFO";

export const FETCH_BUYER_CURRENT_ORDERS = "FETCH_BUYER_CURRENT_ORDERS";
export const FETCH_BUYER_PAST_ORDERS = "FETCH_BUYER_PAST_ORDERS";
export const RESET_BUYER_ORDERS = "RESET_BUYER_ORDERS";

export const FETCH_RESTRO_CURRENT_ORDERS = "FETCH_RESTRO_CURRENT_ORDERS";
export const FETCH_RESTRO_PAST_ORDERS = "FETCH_RESTRO_PAST_ORDERS";
export const RESET_RESTRO_ORDERS = "RESET_RESTRO_ORDERS";

export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
