export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_SUCCESS_MSG = "GET_SUCCESS_MSG";
export const RESET_ALL_STATE = "RESET_ALL_STATE";
export const RESET_SUCCESS_STATE = "RESET_SUCCESS_STATE";
export const RESET_ERROR_STATE = "RESET_ERROR_STATE";

export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const UPDATED_USER_PROFILE = "UPDATED_USER_PROFILE";

export const FETCH_DISABILITIES = "FETCH_DISABILITIES";
export const FETCH_SKILLS = "FETCH_SKILLS";
export const FETCH_QUALIFICATIONS = "FETCH_QUALIFICATIONS";
export const FETCH_EMPLOYMENT_DETAILS = "FETCH_EMPLOYMENT_DETAILS";